spring:
  application:
    name: order-service
  datasource:
    url: ${DATABASE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${PASSWORD}
    username: ${USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: order_success_topic
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false


server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

gateway:
  health:
    check:
      url: http://localhost:8888/actuator/health




