server:
  port: 8888

app:
  api-prefix: /api/v1
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:5174,https://admin.myapp.com"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

resilience4j:
  circuitbreaker:
    instances:
      identityServiceCircuitBreaker:
        failureRateThreshold: 60
        minimumNumberOfCalls: 15
        slidingWindowSize: 30
        waitDurationInOpenState: 20s
        slow-call-duration-threshold: 20s
        slow-call-rate-threshold: 60
      userServiceCircuitBreaker:
        failureRateThreshold: 70
        minimumNumberOfCalls: 15
        slidingWindowSize: 20
        waitDurationInOpenState: 10s
      productServiceCircuitBreaker:
        failureRateThreshold: 70
        minimumNumberOfCalls: 20
        slidingWindowSize: 100
        waitDurationInOpenState: 20s
        slow-call-duration-threshold: 15s
        slow-call-rate-threshold: 70
      orderServiceCircuitBreaker:
          failureRateThreshold: 50
          minimumNumberOfCalls: 15  # Tăng số cuộc gọi tối thiểu để tính tỷ lệ lỗi
          slidingWindowSize: 20     # Tăng cửa sổ trượt để giảm tính nhạy cảm
          slow-call-duration-threshold: 10s  # Giảm thời gian gọi chậm
          slow-call-rate-threshold: 50      # Tăng tỷ lệ chấp nhận cuộc gọi chậm
          waitDurationInOpenState: 10s
      paymentServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      cartServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      notificationServiceCircuitBreaker:
        failureRateThreshold: 70
        minimumNumberOfCalls: 10
        slidingWindowSize: 20
        waitDurationInOpenState: 10s
      reviewServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      chatServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 15  # Tăng số cuộc gọi tối thiểu để tính tỷ lệ lỗi
        slidingWindowSize: 20     # Tăng cửa sổ trượt để giảm tính nhạy cảm
        slow-call-duration-threshold: 10s  # Giảm thời gian gọi chậm
        slow-call-rate-threshold: 50      # Tăng tỷ lệ chấp nhận cuộc gọi chậm
        waitDurationInOpenState: 10s
      recommendationServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 15  # Tăng số cuộc gọi tối thiểu để tính tỷ lệ lỗi
        slidingWindowSize: 20     # Tăng cửa sổ trượt để giảm tính nhạy cảm
        slow-call-duration-threshold: 10s  # Giảm thời gian gọi chậm
        slow-call-rate-threshold: 50      # Tăng tỷ lệ chấp nhận cuộc gọi chậm
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      productServiceCircuitBreaker:
        timeoutDuration: 30s
      orderServiceCircuitBreaker:
        timeoutDuration: 30s
      paymentServiceCircuitBreaker:
        timeoutDuration: 30s
      chatServiceCircuitBreaker:
        timeoutDuration: 30s
      identityServiceCircuitBreaker:
        timeoutDuration: 30s
      userServiceCircuitBreaker:
        timeoutDuration: 30s
      cartServiceCircuitBreaker:
        timeoutDuration: 30s
      notificationServiceCircuitBreaker:
        timeoutDuration: 30s
      reviewServiceCircuitBreaker:
        timeoutDuration: 30s
      recommendationServiceCircuitBreaker:
        timeoutDuration: 30s


#logging:
#  level:
#    ROOT: INFO
#    org.springframework.cloud.gateway: DEBUG
#    io.github.resilience4j.circuitbreaker: DEBUG


spring:
  application:
    name: api-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""
      timeout: 6000ms
      client-type: lettuce
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
#            - name: Retry
#              args:
#                retries: 3
#                backoff:
#                firstBackoff: 100ms
#                maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: identityServiceCircuitBreaker
                fallbackUri: forward:/fallback/identity
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=${app.api-prefix}/user/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/orders
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=${app.api-prefix}/payments/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/payments
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: cartServiceCircuitBreaker
                fallbackUri: forward:/fallback/cart
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/fallback/notification
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=${app.api-prefix}/review/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: reviewServiceCircuitBreaker
                fallbackUri: forward:/fallback/review
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: chatServiceCircuitBreaker
                fallbackUri: forward:/fallback/chat
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=${app.api-prefix}/recommend/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: CircuitBreaker
              args:
                name: recommendationServiceCircuitBreaker
                fallbackUri: forward:/fallback/recommendation
      httpclient:
        connect-timeout: 15000
        response-timeout: 120000ms

management:
  endpoints:
    web:
      exposure:
        include: health, info # expose những endpoint này (hoặc dùng "*" để mở hết)
  endpoint:
    health:
      show-details: always
