  server:
    port: 8086
    servlet:
      context-path: /notification

  spring:
    application:
      name: notification-service

    data:
      mongodb:
        uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
#        uri: mongodb://notification-user:secure-password@mongo:27017/notification-service?authSource=admin

    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: notification-group
        auto-offset-reset: earliest
        properties:
          spring.json.trusted.packages: "*"
          enable.auto.commit: false
      listener:
        ack-mode: manual_immediate
      template:
        default-topic: order_success_topic
      dlq:
        topic: order_success_topic.dlq


  brevo:
    api-key: "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"  # Thay thế bằng API Key của bạn
    sender-email: "tokiejame@gmail.com"  # Email người gửi

  logging:
    level:
      root: INFO
      org.springframework.kafka: DEBUG
