server:
    port: 8080
    servlet:
        context-path: /identity

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/shoes_store_identity"
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

jwt:
    signerKey: "1Tj5jmm5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"


