server:
    port: 8080
    servlet:
        context-path: /identity

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""
      timeout: 6000ms
      client-type: lettuce
  datasource:
    url: "jdbc:mariadb://localhost:3306/shoes_store_identity"
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

jwt:
    signerKey: "1Tj5jmm5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

