server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/shoes_store_users?createDatabaseIfNotExist=true
    driverClassName: org.mariadb.jdbc.Driver
    password: root
    username: root
#    url: jdbc:postgresql://dpg-cv9spthc1ekc738n629g-a.singapore-postgres.render.com:5432/video_call_cjvf
#    driverClassName: org.postgresql.Driver
#    username: video_call_cjvf_user
#    password: UtElJIwBj6AydfrGgbBIR7oRdRIIRgCr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.MariaDBDialect
#postgresql://video_call_cjvf_user:UtElJIwBj6AydfrGgbBIR7oRdRIIRgCr@dpg-cv9spthc1ekc738n629g-a:singapore-postgres:render:com/video_call_cjvf:

